site_name: PPG-beats
repo_url: https://github.com/peterhcharlton/ppg-beats

nav:
    - 'Home': 'index.md'
    - 'Toolbox':
      - 'Getting Started': './toolbox/getting_started.md'
    - 'Datasets':
      - 'Summary': './datasets/summary.md'
    - 'Functions':
    - 'Tutorials':
      - 'Summary': './tutorials/summary.md'
      - 'Performance Assessment': './tutorials/performance_assessment.md'
    